function check_env_settings() { #

	[ "${#PROVISION_DEV_ENV_FOR_BDS_HUB_BACKEND_POLICY_ALWAYS_PROVISION_BREW}" -ge 0 ]

	[ "${#BDS_HUB_BACKEND_SOURCE_DIR_PREFIX}" -gt 0 ] &&
		[ "${BDS_HUB_BACKEND_SOURCE_DIR_PREFIX#/}" != "${BDS_HUB_BACKEND_SOURCE_DIR_PREFIX}" ]

	[ "${#BDS_HUB_BACKEND_SOURCE_DIR_NAME_LIST[@]}" -gt 0 ]

	[ "${#BDS_HUB_BACKEND_SOURCE_VCS_REPO_URL_LIST[@]}" -gt 0 ] &&
		[ "${#BDS_HUB_BACKEND_SOURCE_VCS_REPO_URL_LIST[@]}" -eq "${#BDS_HUB_BACKEND_SOURCE_DIR_NAME_LIST[@]}" ]

	[ "${#BDS_HUB_BACKEND_SSH_DATA_DIR}" -gt 0 ] &&
		[ "${BDS_HUB_BACKEND_SSH_DATA_DIR}" = "${HOME:?}"/.ssh ]

	[ "${#BDS_HUB_BACKEND_SOURCE_VCS_SSH_KEY_PASSWORD_GENERATOR}" -ge 0 ]

	[ "${#BDS_HUB_BACKEND_SOURCE_VCS_SSH_KEY_CANDIDATE_LIST[@]}" -gt 0 ]

	[ "${#BDS_HUB_BACKEND_SOURCE_VCS_SSH_KNOWN_HOST_ENTRY_LIST[@]}" -gt 0 ]
}
